// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using FastFoodManagerPlataformDomain.Entites;
//using FastFoodPlataformPersistencia.Context;

namespace FastFoodPlataformPersistencia.Context
{

    public partial class FastFoodManagerDBContext : DbContext
    {
        public FastFoodManagerDBContext()
        {
        }

        public FastFoodManagerDBContext(DbContextOptions<FastFoodManagerDBContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Carrito> Carritos { get; set; }

        public virtual DbSet<CarritoItem> CarritoItems { get; set; }

        public virtual DbSet<Cliente> Clientes { get; set; }

        public virtual DbSet<Combo> Combos { get; set; }

        public virtual DbSet<ComboProducto> ComboProductos { get; set; }

        public virtual DbSet<Empleado> Empleados { get; set; }

        public virtual DbSet<Pedido> Pedidos { get; set; }

        public virtual DbSet<PedidoItem> PedidoItems { get; set; }

        public virtual DbSet<Producto> Productos { get; set; }

        public virtual DbSet<PromocionProducto> PromocionProductos { get; set; }

        public virtual DbSet<Promocione> Promociones { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see https://go.microsoft.com/fwlink/?LinkId=723263.
            => optionsBuilder.UseSqlServer("Data Source=DESKTOP-0VR82SA;Initial Catalog=FastFoodManagerDB;Integrated Security=True");

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Carrito>(entity =>
            {
                entity.HasKey(e => e.IdCarrito).HasName("PK__Carrito__8B4A618CB55E8DC5");

                entity.ToTable("Carrito");

                entity.Property(e => e.Activo).HasDefaultValue(true);
                entity.Property(e => e.FechaCreacion)
                    .HasDefaultValueSql("(getdate())")
                    .HasColumnType("datetime");

                entity.HasOne(d => d.Cliente).WithMany(p => p.Carritos)
                    .HasForeignKey(d => d.ClienteId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_Carrito_Clientes");
            });

            modelBuilder.Entity<CarritoItem>(entity =>
            {
                entity.HasKey(e => e.Id).HasName("PK__CarritoI__3214EC072A41A136");

                entity.Property(e => e.PrecioUnitario).HasColumnType("decimal(10, 2)");

                entity.HasOne(d => d.Carrito).WithMany(p => p.CarritoItems)
                    .HasForeignKey(d => d.CarritoId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_CarritoItems_Carrito");

                entity.HasOne(d => d.Combo).WithMany(p => p.CarritoItems)
                    .HasForeignKey(d => d.ComboId)
                    .HasConstraintName("FK_CarritoItems_Combo");

                entity.HasOne(d => d.Producto).WithMany(p => p.CarritoItems)
                    .HasForeignKey(d => d.ProductoId)
                    .HasConstraintName("FK_CarritoItems_Producto");
            });

            modelBuilder.Entity<Cliente>(entity =>
            {
                entity.HasKey(e => e.Id).HasName("PK__Clientes__3214EC073C40EF5C");

                entity.HasIndex(e => e.Correo, "UQ__Clientes__60695A19957C5E20").IsUnique();

                entity.HasIndex(e => e.Usuario, "UQ__Clientes__E3237CF70F2CB671").IsUnique();

                entity.Property(e => e.Apellido)
                    .IsRequired()
                    .HasMaxLength(90)
                    .IsUnicode(false);
                entity.Property(e => e.Contraseña)
                    .IsRequired()
                    .HasMaxLength(30)
                    .IsUnicode(false);
                entity.Property(e => e.Correo)
                    .IsRequired()
                    .HasMaxLength(150)
                    .IsUnicode(false);
                entity.Property(e => e.Direccion)
                    .IsRequired()
                    .HasMaxLength(250)
                    .IsUnicode(false);
                entity.Property(e => e.Nombre)
                    .IsRequired()
                    .HasMaxLength(130)
                    .IsUnicode(false);
                entity.Property(e => e.Telefono)
                    .HasMaxLength(30)
                    .IsUnicode(false);
                entity.Property(e => e.Usuario)
                    .HasMaxLength(80)
                    .IsUnicode(false);
            });

            modelBuilder.Entity<Combo>(entity =>
            {
                entity.HasKey(e => e.Id).HasName("PK__Combos__3214EC074D15F962");

                entity.Property(e => e.Activo).HasDefaultValue(true);
                entity.Property(e => e.Nombre)
                    .IsRequired()
                    .HasMaxLength(150)
                    .IsUnicode(false);
                entity.Property(e => e.PrecioCombo).HasColumnType("decimal(10, 2)");
            });

            modelBuilder.Entity<ComboProducto>(entity =>
            {
                entity.HasKey(e => e.Id).HasName("PK__ComboPro__3214EC078A9E1C41");

                entity.Property(e => e.Cantidad).HasDefaultValue(1);

                entity.HasOne(d => d.Combo).WithMany(p => p.ComboProductos)
                    .HasForeignKey(d => d.ComboId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_ComboProductos_Combos");

                entity.HasOne(d => d.Producto).WithMany(p => p.ComboProductos)
                    .HasForeignKey(d => d.ProductoId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_ComboProductos_Productos");
            });

            modelBuilder.Entity<Empleado>(entity =>
            {
                entity.HasKey(e => e.Id).HasName("PK__Empleado__3214EC070EFB871A");

                entity.HasIndex(e => e.Usuario, "UQ__Empleado__E3237CF7565C46DE").IsUnique();

                entity.Property(e => e.Apellido)
                    .IsRequired()
                    .HasMaxLength(80)
                    .IsUnicode(false);
                entity.Property(e => e.Nombre)
                    .IsRequired()
                    .HasMaxLength(80)
                    .IsUnicode(false);
                entity.Property(e => e.Passwordd)
                    .IsRequired()
                    .HasMaxLength(80)
                    .IsUnicode(false);
                entity.Property(e => e.Rol)
                    .IsRequired()
                    .HasMaxLength(50)
                    .IsUnicode(false);
                entity.Property(e => e.Usuario)
                    .IsRequired()
                    .HasMaxLength(80)
                    .IsUnicode(false);
            });

            modelBuilder.Entity<Pedido>(entity =>
            {
                entity.HasKey(e => e.Id).HasName("PK__Pedidos__3214EC077E1FB433");

                entity.Property(e => e.Estado)
                    .IsRequired()
                    .HasMaxLength(50)
                    .IsUnicode(false);
                entity.Property(e => e.Fecha)
                    .HasDefaultValueSql("(getdate())")
                    .HasColumnType("datetime");
                entity.Property(e => e.Total).HasColumnType("decimal(12, 2)");

                entity.HasOne(d => d.Cliente).WithMany(p => p.Pedidos)
                    .HasForeignKey(d => d.ClienteId)
                    .HasConstraintName("FK_Pedidos_Clientes");

                entity.HasOne(d => d.Empleado).WithMany(p => p.Pedidos)
                    .HasForeignKey(d => d.EmpleadoId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_Pedidos_Empleados");
            });

            modelBuilder.Entity<PedidoItem>(entity =>
            {
                entity.HasKey(e => e.Id).HasName("PK__PedidoIt__3214EC078BF696A3");

                entity.Property(e => e.CodigoPedido)
                    .IsRequired()
                    .HasMaxLength(40)
                    .IsUnicode(false);
                entity.Property(e => e.PrecioUnitario).HasColumnType("decimal(10, 2)");
                entity.Property(e => e.Subtotal).HasColumnType("decimal(12, 2)");

                entity.HasOne(d => d.Combo).WithMany(p => p.PedidoItems)
                    .HasForeignKey(d => d.ComboId)
                    .HasConstraintName("FK_PedidoItems_Combos");

                entity.HasOne(d => d.Pedido).WithMany(p => p.PedidoItems)
                    .HasForeignKey(d => d.PedidoId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_PedidoItems_Pedidos");

                entity.HasOne(d => d.Producto).WithMany(p => p.PedidoItems)
                    .HasForeignKey(d => d.ProductoId)
                    .HasConstraintName("FK_PedidoItems_Productos");
            });

            modelBuilder.Entity<Producto>(entity =>
            {
                entity.HasKey(e => e.Id).HasName("PK__Producto__3214EC07B47A0617");

                entity.Property(e => e.Categoria)
                    .HasMaxLength(80)
                    .IsUnicode(false);
                entity.Property(e => e.Descripcion)
                    .HasMaxLength(500)
                    .IsUnicode(false);
                entity.Property(e => e.Disponible).HasDefaultValue(true);
                entity.Property(e => e.Nombre)
                    .IsRequired()
                    .HasMaxLength(150)
                    .IsUnicode(false);
                entity.Property(e => e.Precio).HasColumnType("decimal(10, 2)");
            });

            modelBuilder.Entity<PromocionProducto>(entity =>
            {
                entity.HasKey(e => e.Id).HasName("PK__Promocio__3214EC07895789EF");

                entity.HasOne(d => d.Producto).WithMany(p => p.PromocionProductos)
                    .HasForeignKey(d => d.ProductoId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_PromProd_Productos");

                entity.HasOne(d => d.Promocion).WithMany(p => p.PromocionProductos)
                    .HasForeignKey(d => d.PromocionId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_PromProd_Promociones");
            });

            modelBuilder.Entity<Promocione>(entity =>
            {
                entity.HasKey(e => e.Id).HasName("PK__Promocio__3214EC07BA7DECE9");

                entity.Property(e => e.Activa).HasDefaultValue(true);
                entity.Property(e => e.FechaFin).HasColumnType("datetime");
                entity.Property(e => e.FechaInicio).HasColumnType("datetime");
                entity.Property(e => e.Nombre)
                    .IsRequired()
                    .HasMaxLength(150)
                    .IsUnicode(false);
                entity.Property(e => e.Tipo)
                    .IsRequired()
                    .HasMaxLength(50)
                    .IsUnicode(false);
                entity.Property(e => e.Valor).HasColumnType("decimal(10, 2)");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}