<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="DTOS\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FastFoodManagerPlataformDomain\FastFoodManagerPlataformDomain.csproj" />
    <ProjectReference Include="..\FastFoodPlataformPersistencia\FastFoodPlataformPersistencia.csproj" />
    <ProjectReference Include="..\LoginEmpleado\LoginEmpleado.csproj" />
  </ItemGroup>

</Project>
