// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using FastFoodManagerPlataformDomain.Entites;

namespace FastFoodManagerPlataformDomain.Entites
{

    public partial class Carrito
    {
        public int IdCarrito { get; set; }

        public int ClienteId { get; set; }

        public DateTime? FechaCreacion { get; set; }

        public bool Activo { get; set; }

        public virtual ICollection<CarritoItem> CarritoItems { get; set; } = new List<CarritoItem>();

        public virtual Cliente Cliente { get; set; }

    }
}