// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FastFoodManagerPlataformDomain.Entites
{


    public class CarritoItem
    {
        public int Id { get; set; }

        public int CarritoId { get; set; }

        public int? ProductoId { get; set; }

        public int? ComboId { get; set; }

        public int Cantidad { get; set; }

        public decimal PrecioUnitario { get; set; }

        public virtual Carrito Carrito { get; set; }

        public virtual Combo Combo { get; set; }

        public virtual Producto Producto { get; set; }
    }
}