// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FastFoodManagerPlataformDomain.Entites {
    public partial class Cliente
    {
        public int Id { get; set; }

        public string Correo { get; set; }

        public string Contraseña { get; set; }

        public string Nombre { get; set; }

        public string Apellido { get; set; }

        public string Telefono { get; set; }

        public string Direccion { get; set; }

        public string Usuario { get; set; }

        public virtual ICollection<Carrito> Carritos { get; set; } = new List<Carrito>();

        public virtual ICollection<Pedido> Pedidos { get; set; } = new List<Pedido>();
    }
}

