// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FastFoodManagerPlataformDomain.Entites {
    public partial class Combo
    {
        public int Id { get; set; }

        public string Nombre { get; set; }

        public decimal PrecioCombo { get; set; }

        public bool Activo { get; set; }

        public virtual ICollection<CarritoItem> CarritoItems { get; set; } = new List<CarritoItem>();

        public virtual ICollection<ComboProducto> ComboProductos { get; set; } = new List<ComboProducto>();

        public virtual ICollection<PedidoItem> PedidoItems { get; set; } = new List<PedidoItem>();
    }
}

