// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FastFoodManagerPlataformDomain.Entites {
    public  class Empleado
    {
        public int Id { get; set; }

       public string Nombre { get; set; } = string.Empty;

        public string Apellido { get; set; } = string.Empty;

        public string Usuario { get; set; } = string.Empty;

        public string Passwordd { get; set; } = string.Empty;

        public string Rol { get; set; } = string.Empty;

        public virtual ICollection<Pedido> Pedidos { get; set; } = new List<Pedido>();
    }
}

