// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FastFoodManagerPlataformDomain.Entites {
    public partial class PedidoItem
    {
        public int Id { get; set; }

        public string CodigoPedido { get; set; }

        public int PedidoId { get; set; }

        public int? ProductoId { get; set; }

        public int? ComboId { get; set; }

        public int Cantidad { get; set; }

        public decimal PrecioUnitario { get; set; }

        public decimal Subtotal { get; set; }

        public virtual Combo Combo { get; set; }

        public virtual Pedido Pedido { get; set; }

        public virtual Producto Producto { get; set; }
    }
}

