// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FastFoodManagerPlataformDomain.Entites {
    public partial class Promocione
    {
        public int Id { get; set; }

        public string Nombre { get; set; }

        public string Tipo { get; set; }

        public decimal Valor { get; set; }

        public bool Activa { get; set; }

        public DateTime? FechaInicio { get; set; }

        public DateTime? FechaFin { get; set; }

        public virtual ICollection<PromocionProducto> PromocionProductos { get; set; } = new List<PromocionProducto>();
    }
}

