// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FastFoodManagerPlataformDomain.Entites {
    public partial class PromocionProducto
    {
        public int Id { get; set; }

        public int PromocionId { get; set; }

        public int ProductoId { get; set; }

        public virtual Producto Producto { get; set; }

        public virtual Promocione Promocion { get; set; }
    }
}

