<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="microsoft.data.sqlclient" Version="5.1.6" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FastFoodManagerWebApplication\FastFoodManagerWebApplication.csproj" />
    <ProjectReference Include="..\Menu\Menu.csproj" />
  </ItemGroup>

</Project>